# Generated by Django 5.1.4 on 2025-01-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotegories',
            new_name='Categories',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
